version: '3.3'
services:
#  stats-server:
#    ports:
#      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db-container
    ports:
      - "6540:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
