name: Explore With Me API Tests

on:
  pull_request:

jobs:
  build:
    #uses: yandex-praktikum/java-explore-with-me/.github/workflows/api-tests.yml@ci
    uses: yandex-praktikum/java-explore-with-me-microservices/.github/workflows/api-tests.yml@ci
